// src/js/panels/template-react/main.tsx
import { useEffect, useState } from "react";

import { os, path } from "@lib/node";
import { csi } from "@lib/cep";
import {
  evalES,
  openLinkInBrowser,
  evalTS,
  subscribeBackgroundColor,
} from "@lib/bolt";

import reactLogo from "../../assets/logos/react.svg";
import viteLogo from "../../assets/logos/vite.svg";
import tsLogo from "../../assets/logos/typescript.svg";
import sassLogo from "../../assets/logos/sass.svg";

import nodeJs from "../../assets/logos/node-js.svg";
import adobe from "../../assets/logos/adobe.svg";
import bolt from "../../assets/logos/bolt-cep.svg";

import "../../styles/index.scss";
import "./main.scss";

const Main = () => {
  const [bgColor, setBgColor] = useState("#282c34");
  const [count, setCount] = useState(0);

  //* Demonstration of Traditional string eval-based ExtendScript Interaction
  const jsxTest = () => {
    console.log(evalES(`helloWorld("${csi.getApplicationID()}")`));
  };

  //* Demonstration of End-to-End Type-safe ExtendScript Interaction
  const jsxTestTS = () => {
    evalTS("helloStr", "test").then((res) => {
      console.log(res);
    });

    evalTS("helloNum", 1000).then((res) => {
      console.log(typeof res, res);
    });

    evalTS("helloArrayStr", ["ddddd", "aaaaaa", "zzzzzzz"]).then((res) => {
      console.log(typeof res, res);
    });

    evalTS("helloObj", { height: 90, width: 100 }).then((res) => {
      console.log(typeof res, res); // @ts-ignore
      console.log(res.x); // @ts-ignore
      console.log(res.y);
    });

    evalTS("helloVoid").then(() => {
      console.log("function returning void complete");
    });

    evalTS("helloError", "test").catch((e) => {
      console.log("there was an error", e);
    });
  };

  const nodeTest = () => {
    const folder = path.basename(window.cep_node.global.__dirname);
    alert(
      `Node.js ${process.version}\nPlatform: ${os.platform}\nFolder: ${folder}`
    );
  };

  useEffect(() => {
    if (window.cep) {
      subscribeBackgroundColor(setBgColor);
    }
  }, []);

  return (
    <div className="app" style={{ backgroundColor: bgColor }}>
      <header className="app-header">
        <img src={bolt} className="icon" />
        <div className="stack-icons">
          <div>
            <img src={viteLogo} />
            Vite
          </div>
          +
          <div>
            <img src={reactLogo} />
            React
          </div>
          +
          <div>
            <img src={tsLogo} />
            TypeScript
          </div>
          +
          <div>
            <img src={sassLogo} />
            Sass
          </div>
        </div>
        <div className="button-group">
          <button onClick={() => setCount((count) => count + 1)}>
            Count is: {count}
          </button>
          <button onClick={nodeTest}>
            <img className="icon-button" src={nodeJs} />
          </button>
          <button onClick={jsxTest}>
            <img className="icon-button" src={adobe} />
          </button>
          <button onClick={jsxTestTS}>Ts</button>
        </div>
        <p>
          Edit <code>main.tsx</code> and save to test HMR updates.
        </p>
        <p>
          <button
            className="app-link"
            onClick={() =>
              openLinkInBrowser("https://github.com/hyperbrew/bolt-cep")
            }
          >
            Bolt Docs
          </button>
          {" | "}
          <button
            className="app-link"
            onClick={() => openLinkInBrowser("https://reactjs.org")}
          >
            React Docs
          </button>
          {" | "}
          <button
            className="app-link"
            onClick={() =>
              openLinkInBrowser("https://vitejs.dev/guide/features.html")
            }
          >
            Vite Docs
          </button>
        </p>
      </header>
    </div>
  );
};

export default Main;

// src/js/panels/template-vue/main.vue
<script setup lang="ts">
import { onMounted, ref } from "vue";

import { csi } from "@lib/cep";
import { os, path } from "@lib/node";
import {
  evalES,
  openLinkInBrowser,
  subscribeBackgroundColor,
  evalTS,
} from "@lib/bolt";

import "../../styles/index.scss";
import "./main.scss";

const count = ref(0);
const backgroundColor = ref("#282c34");

//* Demonstration of Traditional string eval-based ExtendScript Interaction
const jsxTest = () => {
  console.log(evalES(`helloWorld("${csi.getApplicationID()}")`));
};

//* Demonstration of End-to-End Type-safe ExtendScript Interaction
const jsxTestTS = () => {
  evalTS("helloStr", "test").then((res) => {
    console.log(res);
  });

  evalTS("helloNum", 1000).then((res) => {
    console.log(typeof res, res);
  });

  evalTS("helloArrayStr", ["ddddd", "aaaaaa", "zzzzzzz"]).then((res) => {
    console.log(typeof res, res);
  });

  evalTS("helloObj", { height: 90, width: 100 }).then((res) => {
    console.log(typeof res, res); // @ts-ignore
    console.log(res.x); // @ts-ignore
    console.log(res.y);
  });

  evalTS("helloVoid").then(() => {
    console.log("function returning void complete");
  });

  evalTS("helloError", "test").catch((e) => {
    console.log("there was an error", e);
  });
};

const nodeTest = () => {
  const folder = path.basename(window.cep_node.global.__dirname);
  alert(
    `Node.js ${process.version}\nPlatform: ${os.platform}\nFolder: ${folder}`
  );
};

onMounted(() => {
  if (window.cep) {
    subscribeBackgroundColor((c: string) => (backgroundColor.value = c));
  }
});
</script>

<template>
  <div class="app" :style="{ backgroundColor: backgroundColor }">
    <header class="app-header">
      <img src="../../assets/logos/bolt-cep.svg" class="icon" />
      <div class="stack-icons">
        <div>
          <img src="../../assets/logos/vite.svg" />
          Vite
        </div>
        +
        <div>
          <img src="../../assets/logos/vue.svg" />
          Vue
        </div>
        +
        <div>
          <img src="../../assets/logos/typescript.svg" />
          TypeScript
        </div>
        +
        <div>
          <img src="../../assets/logos/sass.svg" />
          Sass
        </div>
      </div>
      <div class="button-group">
        <button @click="count++">Count is: {{ count }}</button>
        <button @click="nodeTest">
          <img class="icon-button" src="../../assets/logos/node-js.svg" />
        </button>
        <button @click="jsxTest">
          <img class="icon-button" src="../../assets/logos/adobe.svg" />
        </button>
        <button @click="jsxTestTS">Ts</button>
      </div>

      <p>Edit <code>main.vue</code> and save to test HMR updates.</p>
      <p>
        <button
          @click="
            () => openLinkInBrowser('https://github.com/hyperbrew/bolt-cep')
          "
        >
          Bolt Docs
        </button>
        |
        <button @click="() => openLinkInBrowser('https://v3.vuejs.org/')">
          Vue Docs
        </button>
        |
        <button
          @click="
            () => openLinkInBrowser('https://vitejs.dev/guide/features.html')
          "
        >
          Vite Docs
        </button>
      </p>
    </header>
  </div>
</template>
